const WAVEBAR_RENDER_CONFIG = {
  width: 720,
  height: 110,
  fps: 24,
  barCount: 56,
  barWidth: 8,
  gap: 4,
  bottomPadding: 8,
  baseBarHeight: 5,
  idleTipMin: 1,
  idleTipMax: 5,
  maxTipHeight: 78,
  speakingBoost: 8.2,
  activeSpan: 5.8,
  reactiveSpread: 1.0,
  spreadBias: 0.78,
  smoothingUp: 0.64,
  smoothingDown: 0.18,
  glowStrength: 0.75,
  peakMarker: false,
  mirrorMode: false,
  waveStyle: "podcast",
  borderRadius: 9999,
  historySeconds: 0.95,
  smoothWindowMs: 42,
  xOffset: 0,
  y: 430,
  color: "#FFFFFF",
  colorA: "#22D3EE",
  colorR: "#FB7185",
  colorBoth: "#A78BFA"
};

module.exports = { WAVEBAR_RENDER_CONFIG };
